### ISSUE TITLE
Action response buttons/comments lost formating

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#10]
Something changed in the way the response notes are displayed. They lost nice "font" driven view and look more like std buttons now.

![clipboard01](https://cloud.githubusercontent.com/assets/4722993/5660654/11523440-9723-11e4-90da-7677047a0890.jpg)

**Comment by linwiz** [comment]
The issue is that the link method was causing issues on mobile devices, I'm open to ideas but I had to make the change.
