### ISSUE TITLE
State buttons (green) do not work under IE

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#11]
FireFox is ok ...

**Comment by linwiz** [comment]
I cannot get the page to load at all in IE 11, I'll have to check into this.

**Comment by Paku-** [comment]
I was not able to get the UI working correctly. You know it's not working on some browsers. 
So I started a new UI using some more classic approach (PHP,CSS,AJAX). If you would like to have a look (or help a little) I can push it. It's my first Ajax project but seems I've got the point, at least a little :)
