### ISSUE TITLE
Running on Lighttpd issues.

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#12]
After changing my web server to Lighttpd I am getting a lot of errors in various places.
1.PHPInfo() is running well.
2.myPHPAdmin the same

but GPIO web not ... getting

Fatal error: Call to undefined function scrypt() in /var/www/gpio/scrypt.php on line 177

**Comment by linwiz** [comment]
Lighttpd cannot find the (scrypt)[https://github.com/DomBlack/php-scrypt] library.
 I know nothing of lighttpd, does it support such libraries or do they have to be rewrote for lighttpd?

**Comment by Paku-** [comment]
The one I forgot at the beginning :)
It seems the PHP support should work as usually.
Just need to find proper php.ini now for:

    ;Enable scrypt extension module
    extension=scrypt.so

**Comment by linwiz** [comment]
Right, I forgot about that. If you can find the php.ini for lighttpd you should be good. Maybe try this command
sudo find / -name php.ini

**Comment by Paku-** [comment]
Got it !!
The additional problem was I installed fpm php accellerator (http://php-fpm.org/) ... and just forgot to restart it as well :)

Now running, smoothly on Lighttpd :)
