### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by linwiz** [linwiz/Raspberry-Pi-Web-GPIO#13]
I received random errors last night while the GPIOServer was running but no changes were being made to the pin status.

mysql: error while loading shared libraries: libpthread.so.0: failed to map segment from shared object: Cannot allocate memory
Usage: gpio mode pin mode
Usage: gpio mode pin mode
Usage: gpio write pin value

**Comment by linwiz** [comment]
Commited 9f9b007379b09be9e783ac713dc821eab35bd9b7 as a possible fix for the Usage: gpio errors, not sure of the cause yet but possibly related to the mysql error

**Comment by Paku-** [comment]
got the commit seems to work here

**Comment by linwiz** [comment]
Appears to be fixed.

**Comment by linwiz** [comment]
Received more errors last night.

> {ajax} /www/gpio$ ERROR 2013 (HY000) at line 1: Lost connection to MySQL server                                                                                                               during query
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run
/mysqld/mysqld.sock' (111)
...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run
/mysqld/mysqld.sock' (111)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run
/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run
...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run
/mysqld/mysqld.sock' (2)
 {ajax} /www/gpio$ *** glibc detected *** mysql: corrupted double-linked list: 0
xb7aeaee0 ***

**Comment by Paku-** [comment]
Logs were under rotation so mySQL server was stopped for 2-3sec

**Comment by linwiz** [comment]
That may be hard to fix then. Also I wonder why it is polluting my terminal though and not going into a log file.

**Comment by Paku-** [comment]
Just the idea check it out.

**Comment by Paku-** [comment]
mySQL should allow the logs to rotate without stopping itself.

**Comment by linwiz** [comment]
Possible fix for mysql errors at commit 8f4c00772d4d34a845dd93203e0457bea2a2e879
