### ISSUE TITLE
Strange GPIOServer.sh service behavior

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#15]
I am tring to check if service is running using command like this:

    pgrep -l  GPIOServer.sh

but the response is strange to me.

Some responses show 2 (!) processes ...

    /etc/init.d $ pgrep -l  GPIOServer.sh
    19129 GPIOServer.sh
    23382 GPIOServer.sh
    /etc/init.d $ pgrep -l  GPIOServer.sh
    19129 GPIOServer.sh
    /etc/init.d $ pgrep -l  GPIOServer.sh
    19129 GPIOServer.sh
    23479 GPIOServer.sh
    /etc/init.d $ pgrep -l  GPIOServer.sh
    19129 GPIOServer.sh
    24240 GPIOServer.sh

What's going on ??

Had read somewhere "sleep" could be called as external process ...

**Comment by linwiz** [comment]
I am not sure whats going on with this, it could be a linux related issue rather than GPIOServer.sh
