### ISSUE TITLE
Seems there are some html problems in index.php

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#16]
![gpio](https://cloud.githubusercontent.com/assets/4722993/5701748/33e58bda-9a50-11e4-9059-ae7dd3f4e269.jpg)

**Comment by linwiz** [comment]
I'm not too concerned with this since you are working on a replacement https://github.com/Paku-/Raspberry-Pi-Web-GPIO/tree/ajax

**Comment by Paku-** [comment]
Sorry for that but I did not work on web apps for 15 or more years (!) and always had the Ajax idea in may head so it was just a good time to learn a little ...

It's just poor hand written HTML,PHP and  JS for Ajax like UI plus minimalistic CSS (waiting for CSS guy).
(no imported frameworks)

Had fun any way ... 

It seems beta v1 is ready, do you want me to push it ??

**Comment by linwiz** [comment]
I just checked it out, it looks good, its not mobile friendly yet, but it is a good start. It works faster than what I made and that is a bonus.

**Comment by Paku-** [comment]
Sent the request for stable (?) beta to be pulled
