### ISSUE TITLE
TODO: call the login page only if NOT in debug mode (debugMode=0)

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#25]
as above

**Comment by linwiz** [comment]
You can skip the login by clicking on a link in the navigation, this is not
by design I'm just not sure how to fix it yet.

**Comment by Paku-** [comment]
and I wonder why it takes so much time .... have to learn more on jQuery.

**Comment by linwiz** [comment]
The login process will take time, it is using a secure hashing method called scrypt. scrypt is designed to be slow to thawrt evildoers from bruteforcing a login system or a password hash to crack it.

**Comment by Paku-** [comment]
Ok, but will we go for WWIII with our Pis ? 

but who knows :)

**Comment by linwiz** [comment]
I think the Pi could be used for some kind of weapon defense system lol. It is capable of quite a lot. I don't have any use for such a thing personally.

**Comment by Paku-** [comment]
If we are talking about the login page have in mind that the page /index.php/ is never reloaded. As it Ajax only parts are replaced by the browser. Could be the session variables are not changing ..

**Comment by linwiz** [comment]
I am not sure how to prevent the login from being bypassed at this time, but for now I would consider this issue closed as you do not need to login to develop

**Comment by Paku-** [comment]
Issues are closed if SOLVED :)

**Comment by linwiz** [comment]
I've been unable to fix this issue. I really don't think this is necessary anyway, the login process is very simple. I would rather work on other features than continue to waste time on this one.
