### ISSUE TITLE
TODO: System Configuration table

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#37]
Idea: System wide configuration will be stored inside one row mySQL table.
Options visible and editable on the config.php page.

Possible columns:
1. ShowDisabledPins : boolean
2. Enable SMS integration: boolean
3. Log paging size: int

more to come....

**Comment by linwiz** [comment]
This is fixed in 8b085bd63215144be681a58ad927ae5f310a7cb4

**Comment by Paku-** [comment]
not finished, your solution is little dirty give me few minutes

**Comment by linwiz** [comment]
The idea is implemented, and it works. Also it was your merge request and commits that were the solution, not mine :)

**Comment by Paku-** [comment]
5min pls

**Comment by Paku-** [comment]
ok an hour :)

**Comment by Paku-** [comment]
I am almost ready but have to get out for 1/2h now.

Have no idea how the git will response to next commit to the "ajax"  coming from my 'config' branch.
Have two ideas /think in over/
1. revert your changes .. easy and secure.
2. create new branch at top of the 'ajax' name it 'config2' I will send new pull request to merge 'config' into this one.
Could be there will be no problems so you can merge it later into 'ajax' - if source get mixed we will go with revert.

Think it over I will back in 1/2h.
State your decision here.

**Comment by Paku-** [comment]
So ???
