### ISSUE TITLE
TODO: Cover all pin states (in,out, ALT0..4), introduce the RESET.

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#38]
System has to cover all possible pin states and be able to RESET the board PINs to the default state.
The default state is the proper pins states from electronic (chip) point of view.
Like: 
TxD is output in state ALT0
RxD is input in ??? state 
etc.

introducing reading:
http://93.93.130.214/forums/viewtopic.php?t=79928&p=566660

**Comment by linwiz** [comment]
I'm really not interested in putting time into this feature. I don't have experience enough to code for all possibilities.
