### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#6]
MySQL log table would be a nice enhancement. 
(PIN state change per row)

**Comment by linwiz** [comment]
Logging is enabled in the system logs located at /var/log/GPIOServer.log. I didn't see the need to log into mysql since it is the bash script that does all of the dirty work.. I just used the system logs.

**Comment by Paku-** [comment]
But the user does not have access there ... only the web page.

Thee is no way now to connect and see what happened in the system /on the PINs/ last days...

**Comment by linwiz** [comment]
You're right, there isn't a way to check the log from the browser, but you can check it from the Pi itself, or via SSH. I'll have to think if there is a good way to have the log accessible via web.

**Comment by Paku-** [comment]
Think like user not admin :)

**Comment by linwiz** [comment]
This is now partially fixed in 3f934ccafee0daec74609a46c77460fd76a60cfc. The log is not yet displayed to the user at this time.

**Comment by linwiz** [comment]
Fixed in 4b1451bfdac525da6cf35ec75569186fb7da9846
