### ISSUE TITLE
Log view not refreshed on log update

### ISSUE THREAD

**Issue by Paku-** [linwiz/Raspberry-Pi-Web-GPIO#9]
It seems the log view is not refreshed after log table update. Even after the Log menu button is selected again the view does not change. 

Have to press F5 in the browser to get updated view.

Ideas:
- put auto refresh (like 5 sec)
- or just "refresh" button at top of the view
- or every "Log" menu selection action should "refresh" the underlying view.

**Comment by linwiz** [comment]
What browser do you use? It is working for chrome and mobile chrome(iOS). I will not be able to do an auto refresh, it will interfere with entering information in the forms.

**Comment by Paku-** [comment]
Firefox
________________________________
Od: Matthew Motz<mailto:notifications@github.com>
Wysłano: ‎2015-‎01-‎08 15:19
Do: linwiz/Raspberry-Pi-Web-GPIO<mailto:Raspberry-Pi-Web-GPIO@noreply.github.com>
DW: Paku<mailto:pawel@4x4.org.pl>
Temat: Re: [Raspberry-Pi-Web-GPIO] Log view not refreshed on log update (#9)

What browser do you use? It is working for chrome and mobile chrome(iOS). I will not be able to do an auto refresh, it will interfere with entering information in the forms.

---

**Comment by linwiz** [comment]
I have added a refresh button in 02da7b2b9c9de640b93c8ffbcb4a3669c8c47aba
